#!/bin/bash

# Copyright 2016 Promtech. All rights reserved.
#.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#.
#     http://www.apache.org/licenses/LICENSE-2.0
#.
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu

rm -rf tmp
mkdir -p tmp

host=portal.rusarmyexpo.ru
if [ -n "${1+x}" ]
then
  host=$1
fi

wget -qO- http://$host:8888/changes/getUpdates?revision=0 >tmp/db.json || (echo "ERROR $?!" >&2; exit 1)
dbgen/dump_model >tmp/model.sql

for l in 0 1
do
  echo "Generating db lang=$([ $l = 0 ] && echo ru || echo en)"
  mkdir -p tmp/db/$l
  dbgen/json2sql tmp/db.json $l tmp/db/$l/db.sql
  rm -f ../src/main/assets/db/exhibition_$l ../src/main/assets/db/revision

  (
      cat << EOF
PRAGMA synchronous = OFF;
PRAGMA journal_mode = MEMORY;
PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;
EOF
      cat tmp/model.sql
      cat tmp/db/$l/db.sql
      cat << EOF
CREATE VIEW IF NOT EXISTS schema_search AS
SELECT 'places' entity, id, name FROM places
UNION
SELECT 'events' entity, id, header FROM events
UNION
SELECT 'organizations' entity, id, shortName FROM organizations;
EOF
      echo "COMMIT;"
  ) | sqlite3 ../src/main/assets/db/exhibition_$l
  # | grep -v memory
  cp -f tmp/db/$l/revision ../src/main/assets/db/revision
#  ) | tee tmp/db/$l/all.sql | sqlite3 tmp/db/$l/main | grep -v memory
done

rm -rf tmp
